// Mock data for Voluntaura - Volunteer Opportunity Discovery App

export type Cause = 'Environment' | 'Education' | 'Animals' | 'Health' | 'Food' | 'Community';

export type TimeCommitment = 'One-time' | 'Weekly' | 'Monthly' | 'Flexible';

export type Availability = 'Weekdays' | 'Weekends' | 'Evenings';

export type LocationType = 'Remote' | 'In-person';

export interface Opportunity {
  id: string;
  title: string;
  organization: string;
  description: string;
  shortDescription: string;
  causes: Cause[];
  distance: number; // in miles
  location: string;
  coordinates: { lat: number; lng: number };
  dateTime: string;
  schedule: string;
  timeCommitment: TimeCommitment;
  availability: Availability[];
  locationType: LocationType;
  spotsAvailable: number;
  totalSpots: number;
  requirements: string[];
  contactEmail: string;
  contactPhone: string;
  imageUrl: string;
  duration: string;
}

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Lake Woodlands Cleanup',
    organization: 'The Woodlands Township',
    description: 'Join us for our monthly lake cleanup event! Help us keep Lake Woodlands beautiful and protect local wildlife from harmful debris. Kayaks and cleanup supplies provided.',
    shortDescription: 'Help clean up Lake Woodlands and protect local wildlife.',
    causes: ['Environment', 'Community'],
    distance: 2.3,
    location: 'Northshore Park, The Woodlands, Texas',
    coordinates: { lat: 30.1666, lng: -95.4660 },
    dateTime: 'Saturday, Feb 15, 9:00 AM',
    schedule: 'Every 3rd Saturday',
    timeCommitment: 'Monthly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 12,
    totalSpots: 30,
    requirements: ['Comfortable outdoor clothing', 'Sunscreen recommended', 'Kayaking experience a plus'],
    contactEmail: 'environmental@thewoodlandstownship-tx.gov',
    contactPhone: '(281) 210-3800',
    imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800',
    duration: '3 hours',
  },
  {
    id: '2',
    title: 'After-School Tutoring',
    organization: 'Interfaith of The Woodlands',
    description: 'Make a difference in a child\'s life by helping with homework and reading at our local community centers. Matches based on subjects and grade levels.',
    shortDescription: 'Tutor local students in reading and math.',
    causes: ['Education'],
    distance: 1.5,
    location: 'The Woodlands, Texas',
    coordinates: { lat: 30.1583, lng: -95.4891 },
    dateTime: 'Weekdays 3:30 PM - 5:30 PM',
    schedule: 'Flexible weekday afternoons',
    timeCommitment: 'Weekly',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 8,
    totalSpots: 20,
    requirements: ['Background check required', 'Age 18+', 'High school diploma'],
    contactEmail: 'tutors@brightfutures.edu',
    contactPhone: '(213) 555-0456',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800',
    duration: '2 hours per session',
  },
  {
    id: '3',
    title: 'Animal Shelter Helper',
    organization: 'Montgomery County Animal Shelter',
    description: 'Help care for rescued dogs and cats awaiting their forever homes. Tasks include feeding, walking dogs, socializing animals, and helping with adoption events.',
    shortDescription: 'Care for shelter animals and help with adoptions.',
    causes: ['Animals'],
    distance: 4.2,
    location: 'Montgomery County Animal Shelter, Conroe, Texas',
    coordinates: { lat: 30.2222, lng: -95.4566 },
    dateTime: 'Open shifts daily',
    schedule: 'Flexible scheduling',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'In-person',
    spotsAvailable: 15,
    totalSpots: 40,
    requirements: ['Age 16+', 'Comfortable with animals', 'Tetanus vaccination'],
    contactEmail: 'volunteer@happypaws.org',
    contactPhone: '(818) 555-0789',
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    duration: '3-4 hours per shift',
  },
  {
    id: '4',
    title: 'Vegetable Garden Volunteer',
    organization: 'Veggie Village',
    description: 'Help maintain our community donation garden that provides fresh produce to local food pantries. Learn organic gardening techniques while helping feed the community.',
    shortDescription: 'Grow organic produce for local food banks.',
    causes: ['Environment', 'Food', 'Community'],
    distance: 0.8,
    location: 'Alden Bridge Sports Park, The Woodlands, Texas',
    coordinates: { lat: 30.1989, lng: -95.5042 },
    dateTime: 'Saturdays 8:00 AM - 12:00 PM',
    schedule: 'Every Saturday morning',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 6,
    totalSpots: 15,
    requirements: ['Able to do light physical work', 'Gardening gloves provided'],
    contactEmail: 'garden@greenthumb.org',
    contactPhone: '(626) 555-0321',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    duration: '4 hours',
  },
  {
    id: '5',
    title: 'Hospital Volunteer',
    organization: 'Houston Methodist The Woodlands',
    description: 'Assist hospital staff and bring comfort to patients by providing friendly conversation and companionship. Various roles available throughout the hospital.',
    shortDescription: 'Support patients and staff at Houston Methodist.',
    causes: ['Health', 'Community'],
    distance: 3.1,
    location: 'Houston Methodist, The Woodlands, Texas',
    coordinates: { lat: 30.2052, lng: -95.4526 },
    dateTime: 'Flexible visiting hours',
    schedule: 'Flexible scheduling',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends'],
    locationType: 'In-person',
    spotsAvailable: 20,
    totalSpots: 50,
    requirements: ['Background check', 'Health screening', 'Age 18+', 'Flu vaccination'],
    contactEmail: 'volunteer@healinghearts.med',
    contactPhone: '(818) 555-0500',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800',
    duration: '2-3 hours per visit',
  },
  {
    id: '6',
    title: 'Food Bank Sorting',
    organization: 'Montgomery County Food Bank',
    description: 'Help sort and package food donations that will be distributed to families in need across the county. Great for groups and team-building!',
    shortDescription: 'Sort food donations for families in need.',
    causes: ['Food', 'Community'],
    distance: 5.4,
    location: 'Montgomery County Food Bank, Conroe, Texas',
    coordinates: { lat: 30.3475, lng: -95.4354 },
    dateTime: 'Tuesday & Thursday 6:00 PM - 9:00 PM',
    schedule: 'Twice weekly evenings',
    timeCommitment: 'Weekly',
    availability: ['Evenings'],
    locationType: 'In-person',
    spotsAvailable: 25,
    totalSpots: 60,
    requirements: ['Closed-toe shoes', 'Able to stand for extended periods'],
    contactEmail: 'help@lafoodproject.org',
    contactPhone: '(310) 555-0888',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd59a0c3a9b1?w=800',
    duration: '3 hours',
  },
  {
    id: '7',
    title: 'Virtual Crisis Counselor',
    organization: 'Hope Line',
    description: 'Provide text-based support to people in crisis from the comfort of your home. Comprehensive training program included. Make a life-saving difference.',
    shortDescription: 'Text-based crisis support from home.',
    causes: ['Health', 'Community'],
    distance: 0,
    location: 'Remote - Work from home',
    coordinates: { lat: 30.1666, lng: -95.4660 },
    dateTime: '4-hour shifts, 24/7 available',
    schedule: 'Flexible remote shifts',
    timeCommitment: 'Weekly',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'Remote',
    spotsAvailable: 30,
    totalSpots: 100,
    requirements: ['Age 18+', 'Complete 30-hour training', 'Reliable internet', '6-month commitment'],
    contactEmail: 'training@hopeline.org',
    contactPhone: '(800) 555-HOPE',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
    duration: '4 hours per shift',
  },
  {
    id: '8',
    title: 'Nature Trail Maintenance',
    organization: 'George Mitchell Nature Preserve',
    description: 'Help maintain and restore hiking and biking trails in the preserve. Activities include clearing brush, repairing erosion damage, and general trail upkeep.',
    shortDescription: 'Maintain trails in the George Mitchell Nature Preserve.',
    causes: ['Environment', 'Community'],
    distance: 8.7,
    location: 'George Mitchell Nature Preserve, The Woodlands, Texas',
    coordinates: { lat: 30.1500, lng: -95.5000 },
    dateTime: 'Sundays 7:00 AM - 1:00 PM',
    schedule: 'Weekly Sunday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 10,
    totalSpots: 25,
    requirements: ['Good physical fitness', 'Hiking boots required', 'Bring water and snacks'],
    contactEmail: 'trails@trailsfortomorrow.org',
    contactPhone: '(323) 555-0877',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    duration: '6 hours',
  },
  {
    id: '9',
    title: 'Senior Tech Helper',
    organization: 'The Woodlands Senior Center',
    description: 'Help local seniors learn to use smartphones, tablets, and computers. Teach video calling, email, online safety, and more.',
    shortDescription: 'Teach seniors to use technology.',
    causes: ['Education', 'Community'],
    distance: 2.9,
    location: 'The Woodlands Community Center, The Woodlands, Texas',
    coordinates: { lat: 30.1565, lng: -95.4856 },
    dateTime: 'Wednesdays 10:00 AM - 12:00 PM',
    schedule: 'Weekly Wednesday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 5,
    totalSpots: 12,
    requirements: ['Patience with older adults', 'Basic tech knowledge', 'Clear communication'],
    contactEmail: 'connect@digitalbridges.org',
    contactPhone: '(626) 555-0245',
    imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    duration: '2 hours',
  },
  {
    id: '10',
    title: 'Invasive Species Removal',
    organization: 'The Woodlands Township',
    description: 'Help remove invasive non-native plants from our local parks and greenbelts to protect native habitats. Learn about local ecosystems while making a difference.',
    shortDescription: 'Remove invasive species from local parks.',
    causes: ['Environment', 'Animals'],
    distance: 6.2,
    location: 'Various Parks, The Woodlands, Texas',
    coordinates: { lat: 30.1666, lng: -95.4660 },
    dateTime: 'First Saturday of each month, 9:00 AM',
    schedule: 'Monthly restoration days',
    timeCommitment: 'Monthly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 18,
    totalSpots: 35,
    requirements: ['Long pants and closed-toe shoes', 'Sun protection'],
    contactEmail: 'restore@nativespecies.org',
    contactPhone: '(310) 555-0962',
    imageUrl: 'https://images.unsplash.com/photo-1500829243541-74b677fecc30?w=800',
    duration: '4 hours',
  },
  {
    id: '11',
    title: 'Youth Sports Coach',
    organization: 'South County Football League',
    description: 'Coach youth football or cheer for local teams. No professional experience needed - just enthusiasm and a love for mentoring kids!',
    shortDescription: 'Coach youth sports in The Woodlands.',
    causes: ['Education', 'Community', 'Health'],
    distance: 3.8,
    location: 'Gullo Park, The Woodlands, Texas',
    coordinates: { lat: 30.1800, lng: -95.4500 },
    dateTime: 'Saturdays 9:00 AM - 12:00 PM',
    schedule: '10-week season commitment',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 8,
    totalSpots: 20,
    requirements: ['Background check', 'Age 21+', 'Basic knowledge of chosen sport'],
    contactEmail: 'coaches@kidsplay.org',
    contactPhone: '(323) 555-0438',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934- voices?w=800',
    duration: '3 hours + practice planning',
  },
  {
    id: '12',
    title: 'Community Outreach',
    organization: 'Interfaith of The Woodlands',
    description: 'Join outreach teams that connect with individuals in need, providing essentials and information about available services and resources.',
    shortDescription: 'Connect individuals with community resources.',
    causes: ['Community', 'Health'],
    distance: 1.2,
    location: 'Interfaith, The Woodlands, Texas',
    coordinates: { lat: 30.1583, lng: -95.4891 },
    dateTime: 'Thursday evenings 6:00 PM - 9:00 PM',
    schedule: 'Weekly evening outreach',
    timeCommitment: 'Weekly',
    availability: ['Evenings'],
    locationType: 'In-person',
    spotsAvailable: 4,
    totalSpots: 10,
    requirements: ['Training session required', 'Comfortable walking', 'Non-judgmental attitude'],
    contactEmail: 'outreach@streetstohome.org',
    contactPhone: '(213) 555-0112',
    imageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800',
    duration: '3 hours',
  },
  {
    id: '13',
    title: 'Library Reading Buddy',
    organization: 'South Regional Library',
    description: 'Read with children at the library to promote literacy and a love of books. Perfect for book lovers who want to inspire the next generation.',
    shortDescription: 'Read with children at the local library.',
    causes: ['Education'],
    distance: 1.9,
    location: 'South Regional Library, The Woodlands, Texas',
    coordinates: { lat: 30.1600, lng: -95.4700 },
    dateTime: 'Saturdays 10:00 AM - 12:00 PM',
    schedule: 'Weekly Saturday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 10,
    totalSpots: 25,
    requirements: ['Love of reading', 'Background check', 'Age 16+'],
    contactEmail: 'read@readtogetherla.org',
    contactPhone: '(213) 555-0119',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    duration: '2 hours',
  },
  {
    id: '14',
    title: 'Meal Delivery Driver',
    organization: 'Meals on Wheels Montgomery County',
    description: 'Deliver nutritious meals to homebound seniors in The Woodlands and surrounding areas. Use your own vehicle to bring food and friendly check-ins.',
    shortDescription: 'Deliver meals to homebound seniors.',
    causes: ['Food', 'Health', 'Community'],
    distance: 2.5,
    location: 'Routes throughout The Woodlands, Texas',
    coordinates: { lat: 30.1666, lng: -95.4660 },
    dateTime: 'Weekdays 11:00 AM - 1:00 PM',
    schedule: 'Flexible weekday lunchtimes',
    timeCommitment: 'Flexible',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 15,
    totalSpots: 40,
    requirements: ['Valid driver\'s license', 'Reliable vehicle', 'Auto insurance', 'Background check'],
    contactEmail: 'drivers@mowla.org',
    contactPhone: '(213) 555-0225',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800',
    duration: '2 hours per route',
  },
  {
    id: '15',
    title: 'Storm Drain Marker',
    organization: 'The Woodlands Township',
    description: 'Help place markers on storm drains to remind the community that "Storm Drains Drain to Waterways". A flexible volunteer opportunity for families and groups.',
    shortDescription: 'Mark storm drains to protect local waterways.',
    causes: ['Environment', 'Education'],
    distance: 0,
    location: 'Various neighborhoods, The Woodlands, Texas',
    coordinates: { lat: 30.1666, lng: -95.4660 },
    dateTime: 'Flexible scheduling',
    schedule: 'Self-paced data collection',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends'],
    locationType: 'In-person',
    spotsAvailable: 50,
    totalSpots: 200,
    requirements: ['Smartphone with GPS', 'Attention to detail', 'Enjoy being outdoors'],
    contactEmail: 'science@citizensciencecorps.org',
    contactPhone: '(800) 555-DATA',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
    duration: '1-4 hours per session',
  },
  {
    id: '16',
    title: 'Disaster Relief Volunteer',
    organization: 'Montgomery County Office of Emergency Management',
    description: 'Be trained and ready to respond when disasters strike. Help with shelter operations, supply distribution, and community support during emergencies.',
    shortDescription: 'Help communities during emergencies.',
    causes: ['Community', 'Health'],
    distance: 4.5,
    location: 'Emergency Operations Center, Conroe, Texas',
    coordinates: { lat: 30.3113, lng: -95.4558 },
    dateTime: 'On-call after training',
    schedule: 'Training + on-call deployment',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'In-person',
    spotsAvailable: 25,
    totalSpots: 100,
    requirements: ['Complete disaster response training', 'Flexible availability', 'Physical fitness'],
    contactEmail: 'ready@readyresponse.org',
    contactPhone: '(310) 555-0945',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800',
    duration: 'Varies by deployment',
  },
];

export const causeColors: Record<Cause, string> = {
  Environment: 'cause-badge-environment',
  Education: 'cause-badge-education',
  Animals: 'cause-badge-animals',
  Health: 'cause-badge-health',
  Food: 'cause-badge-food',
  Community: 'cause-badge-community',
};

export const causeIcons: Record<Cause, string> = {
  Environment: '🌿',
  Education: '📚',
  Animals: '🐾',
  Health: '❤️',
  Food: '🍎',
  Community: '🏘️',
};
