// Mock data for Voluntaura - Volunteer Opportunity Discovery App

export type Cause = 'Environment' | 'Education' | 'Animals' | 'Health' | 'Food' | 'Community';

export type TimeCommitment = 'One-time' | 'Weekly' | 'Monthly' | 'Flexible';

export type Availability = 'Weekdays' | 'Weekends' | 'Evenings';

export type LocationType = 'Remote' | 'In-person';

export interface Opportunity {
  id: string;
  title: string;
  organization: string;
  description: string;
  shortDescription: string;
  causes: Cause[];
  distance: number; // in miles
  location: string;
  coordinates: { lat: number; lng: number };
  dateTime: string;
  schedule: string;
  timeCommitment: TimeCommitment;
  availability: Availability[];
  locationType: LocationType;
  spotsAvailable: number;
  totalSpots: number;
  requirements: string[];
  contactEmail: string;
  contactPhone: string;
  imageUrl: string;
  duration: string;
}

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Beach Cleanup Day',
    organization: 'Ocean Guardians',
    description: 'Join us for our monthly beach cleanup event! We provide all supplies including gloves, bags, and grabbers. Help us keep our coastline beautiful and protect marine life from harmful debris. All ages welcome, perfect for families!',
    shortDescription: 'Help clean up local beaches and protect marine wildlife.',
    causes: ['Environment', 'Community'],
    distance: 2.3,
    location: '1200 Ocean Drive, Santa Monica, CA',
    coordinates: { lat: 34.0195, lng: -118.4912 },
    dateTime: 'Saturday, Feb 15, 9:00 AM',
    schedule: 'Every 3rd Saturday',
    timeCommitment: 'Monthly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 12,
    totalSpots: 30,
    requirements: ['Comfortable outdoor clothing', 'Sunscreen recommended'],
    contactEmail: 'volunteer@oceanguardians.org',
    contactPhone: '(310) 555-0123',
    imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800',
    duration: '3 hours',
  },
  {
    id: '2',
    title: 'After-School Tutoring',
    organization: 'Bright Futures Academy',
    description: 'Make a difference in a child\'s life by helping with homework and reading. We match tutors with students based on subjects and grade levels. Training provided for all new volunteers.',
    shortDescription: 'Tutor elementary students in reading and math.',
    causes: ['Education'],
    distance: 1.5,
    location: '456 Learning Lane, Los Angeles, CA',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    dateTime: 'Weekdays 3:30 PM - 5:30 PM',
    schedule: 'Flexible weekday afternoons',
    timeCommitment: 'Weekly',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 8,
    totalSpots: 20,
    requirements: ['Background check required', 'Age 18+', 'High school diploma'],
    contactEmail: 'tutors@brightfutures.edu',
    contactPhone: '(213) 555-0456',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800',
    duration: '2 hours per session',
  },
  {
    id: '3',
    title: 'Animal Shelter Helper',
    organization: 'Happy Paws Rescue',
    description: 'Help care for rescued dogs and cats awaiting their forever homes. Tasks include feeding, walking dogs, socializing animals, and assisting with adoption events.',
    shortDescription: 'Care for shelter animals and help with adoptions.',
    causes: ['Animals'],
    distance: 4.2,
    location: '789 Pet Haven Road, Burbank, CA',
    coordinates: { lat: 34.1808, lng: -118.3089 },
    dateTime: 'Open shifts daily',
    schedule: 'Flexible scheduling',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'In-person',
    spotsAvailable: 15,
    totalSpots: 40,
    requirements: ['Age 16+', 'Comfortable with animals', 'Tetanus vaccination'],
    contactEmail: 'volunteer@happypaws.org',
    contactPhone: '(818) 555-0789',
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    duration: '3-4 hours per shift',
  },
  {
    id: '4',
    title: 'Community Garden Volunteer',
    organization: 'Green Thumb Collective',
    description: 'Help maintain our community garden that provides fresh produce to local food banks. Learn organic gardening techniques while making a positive environmental impact.',
    shortDescription: 'Grow organic produce for local food banks.',
    causes: ['Environment', 'Food', 'Community'],
    distance: 0.8,
    location: '321 Garden Way, Pasadena, CA',
    coordinates: { lat: 34.1478, lng: -118.1445 },
    dateTime: 'Saturdays 8:00 AM - 12:00 PM',
    schedule: 'Every Saturday morning',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 6,
    totalSpots: 15,
    requirements: ['Able to do light physical work', 'Gardening gloves provided'],
    contactEmail: 'garden@greenthumb.org',
    contactPhone: '(626) 555-0321',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    duration: '4 hours',
  },
  {
    id: '5',
    title: 'Hospital Patient Visitor',
    organization: 'Healing Hearts Hospital',
    description: 'Bring comfort to patients by providing friendly conversation and companionship. Perfect for those with empathy and good listening skills.',
    shortDescription: 'Provide companionship to hospital patients.',
    causes: ['Health', 'Community'],
    distance: 3.1,
    location: '500 Medical Center Drive, Glendale, CA',
    coordinates: { lat: 34.1425, lng: -118.2551 },
    dateTime: 'Flexible visiting hours',
    schedule: 'Flexible scheduling',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends'],
    locationType: 'In-person',
    spotsAvailable: 20,
    totalSpots: 50,
    requirements: ['Background check', 'Health screening', 'Age 18+', 'Flu vaccination'],
    contactEmail: 'volunteer@healinghearts.med',
    contactPhone: '(818) 555-0500',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800',
    duration: '2-3 hours per visit',
  },
  {
    id: '6',
    title: 'Food Bank Sorting',
    organization: 'LA Food Project',
    description: 'Help sort and package food donations that will be distributed to families in need. Great for groups and team-building events!',
    shortDescription: 'Sort food donations for families in need.',
    causes: ['Food', 'Community'],
    distance: 5.4,
    location: '888 Giving Boulevard, Culver City, CA',
    coordinates: { lat: 34.0211, lng: -118.3965 },
    dateTime: 'Tuesday & Thursday 6:00 PM - 9:00 PM',
    schedule: 'Twice weekly evenings',
    timeCommitment: 'Weekly',
    availability: ['Evenings'],
    locationType: 'In-person',
    spotsAvailable: 25,
    totalSpots: 60,
    requirements: ['Closed-toe shoes', 'Able to stand for extended periods'],
    contactEmail: 'help@lafoodproject.org',
    contactPhone: '(310) 555-0888',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd59a0c3a9b1?w=800',
    duration: '3 hours',
  },
  {
    id: '7',
    title: 'Virtual Crisis Counselor',
    organization: 'Hope Line',
    description: 'Provide text-based support to people in crisis from the comfort of your home. Comprehensive training program included. Make a life-saving difference.',
    shortDescription: 'Text-based crisis support from home.',
    causes: ['Health', 'Community'],
    distance: 0,
    location: 'Remote - Work from home',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    dateTime: '4-hour shifts, 24/7 available',
    schedule: 'Flexible remote shifts',
    timeCommitment: 'Weekly',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'Remote',
    spotsAvailable: 30,
    totalSpots: 100,
    requirements: ['Age 18+', 'Complete 30-hour training', 'Reliable internet', '6-month commitment'],
    contactEmail: 'training@hopeline.org',
    contactPhone: '(800) 555-HOPE',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
    duration: '4 hours per shift',
  },
  {
    id: '8',
    title: 'Trail Maintenance Crew',
    organization: 'Trails for Tomorrow',
    description: 'Help maintain and restore hiking trails in local parks. Activities include clearing brush, repairing erosion damage, and building trail features.',
    shortDescription: 'Maintain hiking trails in local parks.',
    causes: ['Environment', 'Community'],
    distance: 8.7,
    location: 'Griffith Park, Los Angeles, CA',
    coordinates: { lat: 34.1341, lng: -118.2943 },
    dateTime: 'Sundays 7:00 AM - 1:00 PM',
    schedule: 'Weekly Sunday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 10,
    totalSpots: 25,
    requirements: ['Good physical fitness', 'Hiking boots required', 'Bring water and snacks'],
    contactEmail: 'trails@trailsfortomorrow.org',
    contactPhone: '(323) 555-0877',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    duration: '6 hours',
  },
  {
    id: '9',
    title: 'Senior Tech Helper',
    organization: 'Digital Bridges',
    description: 'Help seniors learn to use smartphones, tablets, and computers. Teach video calling, email, online safety, and more. Patience and clear communication skills essential.',
    shortDescription: 'Teach seniors to use technology.',
    causes: ['Education', 'Community'],
    distance: 2.9,
    location: '245 Senior Center Way, Arcadia, CA',
    coordinates: { lat: 34.1397, lng: -118.0353 },
    dateTime: 'Wednesdays 10:00 AM - 12:00 PM',
    schedule: 'Weekly Wednesday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 5,
    totalSpots: 12,
    requirements: ['Patience with older adults', 'Basic tech knowledge', 'Clear communication'],
    contactEmail: 'connect@digitalbridges.org',
    contactPhone: '(626) 555-0245',
    imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
    duration: '2 hours',
  },
  {
    id: '10',
    title: 'Wildlife Habitat Restoration',
    organization: 'Native Species Alliance',
    description: 'Help restore native plant habitats for local wildlife. Learn about native species and ecosystems while getting your hands dirty!',
    shortDescription: 'Restore native habitats for local wildlife.',
    causes: ['Environment', 'Animals'],
    distance: 6.2,
    location: 'Ballona Wetlands, Playa del Rey, CA',
    coordinates: { lat: 33.9617, lng: -118.4392 },
    dateTime: 'First Saturday of each month, 9:00 AM',
    schedule: 'Monthly restoration days',
    timeCommitment: 'Monthly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 18,
    totalSpots: 35,
    requirements: ['Long pants and closed-toe shoes', 'Sun protection'],
    contactEmail: 'restore@nativespecies.org',
    contactPhone: '(310) 555-0962',
    imageUrl: 'https://images.unsplash.com/photo-1500829243541-74b677fecc30?w=800',
    duration: '4 hours',
  },
  {
    id: '11',
    title: 'Youth Sports Coach',
    organization: 'Kids Play Foundation',
    description: 'Coach youth basketball, soccer, or baseball for underserved communities. No professional experience needed - just enthusiasm and a love for kids!',
    shortDescription: 'Coach youth sports in underserved areas.',
    causes: ['Education', 'Community', 'Health'],
    distance: 3.8,
    location: 'Various locations in East LA',
    coordinates: { lat: 34.0239, lng: -118.1721 },
    dateTime: 'Saturdays 9:00 AM - 12:00 PM',
    schedule: '10-week season commitment',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 8,
    totalSpots: 20,
    requirements: ['Background check', 'Age 21+', 'Basic knowledge of chosen sport'],
    contactEmail: 'coaches@kidsplay.org',
    contactPhone: '(323) 555-0438',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934- voices?w=800',
    duration: '3 hours + practice planning',
  },
  {
    id: '12',
    title: 'Homeless Outreach Team',
    organization: 'Streets to Home',
    description: 'Join outreach teams that connect with homeless individuals, providing essentials and information about available services and housing resources.',
    shortDescription: 'Connect homeless individuals with resources.',
    causes: ['Community', 'Health'],
    distance: 1.2,
    location: 'Downtown Los Angeles, CA',
    coordinates: { lat: 34.0407, lng: -118.2468 },
    dateTime: 'Thursday evenings 6:00 PM - 9:00 PM',
    schedule: 'Weekly evening outreach',
    timeCommitment: 'Weekly',
    availability: ['Evenings'],
    locationType: 'In-person',
    spotsAvailable: 4,
    totalSpots: 10,
    requirements: ['Training session required', 'Comfortable walking', 'Non-judgmental attitude'],
    contactEmail: 'outreach@streetstohome.org',
    contactPhone: '(213) 555-0112',
    imageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800',
    duration: '3 hours',
  },
  {
    id: '13',
    title: 'Library Reading Buddy',
    organization: 'Read Together LA',
    description: 'Read with children at local libraries to promote literacy and a love of books. Perfect for book lovers who want to inspire the next generation.',
    shortDescription: 'Read with children at local libraries.',
    causes: ['Education'],
    distance: 1.9,
    location: 'Central Library, Los Angeles, CA',
    coordinates: { lat: 34.0499, lng: -118.2559 },
    dateTime: 'Saturdays 10:00 AM - 12:00 PM',
    schedule: 'Weekly Saturday mornings',
    timeCommitment: 'Weekly',
    availability: ['Weekends'],
    locationType: 'In-person',
    spotsAvailable: 10,
    totalSpots: 25,
    requirements: ['Love of reading', 'Background check', 'Age 16+'],
    contactEmail: 'read@readtogetherla.org',
    contactPhone: '(213) 555-0119',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    duration: '2 hours',
  },
  {
    id: '14',
    title: 'Meal Delivery Driver',
    organization: 'Meals on Wheels LA',
    description: 'Deliver nutritious meals to homebound seniors. Use your own vehicle to bring food and friendly check-ins to those who need it most.',
    shortDescription: 'Deliver meals to homebound seniors.',
    causes: ['Food', 'Health', 'Community'],
    distance: 2.5,
    location: 'Routes throughout Los Angeles',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    dateTime: 'Weekdays 11:00 AM - 1:00 PM',
    schedule: 'Flexible weekday lunchtimes',
    timeCommitment: 'Flexible',
    availability: ['Weekdays'],
    locationType: 'In-person',
    spotsAvailable: 15,
    totalSpots: 40,
    requirements: ['Valid driver\'s license', 'Reliable vehicle', 'Auto insurance', 'Background check'],
    contactEmail: 'drivers@mowla.org',
    contactPhone: '(213) 555-0225',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800',
    duration: '2 hours per route',
  },
  {
    id: '15',
    title: 'Environmental Data Collector',
    organization: 'Citizen Science Corps',
    description: 'Help collect environmental data for research projects. Activities include water quality testing, bird counting, and plant surveys. Training provided!',
    shortDescription: 'Collect data for environmental research.',
    causes: ['Environment', 'Education'],
    distance: 0,
    location: 'Various locations + Remote data entry',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    dateTime: 'Flexible scheduling',
    schedule: 'Self-paced data collection',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends'],
    locationType: 'In-person',
    spotsAvailable: 50,
    totalSpots: 200,
    requirements: ['Smartphone with GPS', 'Attention to detail', 'Enjoy being outdoors'],
    contactEmail: 'science@citizensciencecorps.org',
    contactPhone: '(800) 555-DATA',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
    duration: '1-4 hours per session',
  },
  {
    id: '16',
    title: 'Disaster Relief Volunteer',
    organization: 'Ready Response Team',
    description: 'Be trained and ready to respond when disasters strike. Help with shelter operations, supply distribution, and community support during emergencies.',
    shortDescription: 'Help communities during emergencies.',
    causes: ['Community', 'Health'],
    distance: 4.5,
    location: 'Training Center, Torrance, CA',
    coordinates: { lat: 33.8358, lng: -118.3406 },
    dateTime: 'On-call after training',
    schedule: 'Training + on-call deployment',
    timeCommitment: 'Flexible',
    availability: ['Weekdays', 'Weekends', 'Evenings'],
    locationType: 'In-person',
    spotsAvailable: 25,
    totalSpots: 100,
    requirements: ['Complete disaster response training', 'Flexible availability', 'Physical fitness'],
    contactEmail: 'ready@readyresponse.org',
    contactPhone: '(310) 555-0945',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800',
    duration: 'Varies by deployment',
  },
];

export const causeColors: Record<Cause, string> = {
  Environment: 'cause-badge-environment',
  Education: 'cause-badge-education',
  Animals: 'cause-badge-animals',
  Health: 'cause-badge-health',
  Food: 'cause-badge-food',
  Community: 'cause-badge-community',
};

export const causeIcons: Record<Cause, string> = {
  Environment: '🌿',
  Education: '📚',
  Animals: '🐾',
  Health: '❤️',
  Food: '🍎',
  Community: '🏘️',
};
